### ISSUE TITLE
Customise the images 

### ISSUE THREAD

**Issue by BatoolMM** [ARab-R/ARab_R#9]
@Hussain-Alsalman can you fix the dimension for the image in [this page](https://arab-r.github.io/ARab_R/posts/welcoming-messege/), please?

**Comment by Hussain-Alsalman** [comment]
Post thumbnails are behaving as expected. Generally, you would want to upload wide images for thumbnails, because they are set to try to consume full page width. As such, squarish or equal sides images will always appear enlarged. A good example of wide image can be found [here](http://localhost:1313/ARab_R/posts/onboarding-process-r-ladies/). 

As for this specific post, I would recommend that you embed any square images inside the post content itself if you must.
